### PR TITLE
Cast string to bytes for python 3 compatibility

### PR DESCRIPTION
**Pull request by davenquinn**

### CODE REVIEW

**Comment by davenquinn** [comment]
Hi @jwass, are you interested in merging this? Seems like low-hanging fruit.

**Comment by jwass** [comment]
Hi @davenquinn. Totally forgot about this. Can you squash into a single commit?

**Comment by davenquinn** [comment]
Can't you squash on merge? That might be easier than rewriting my history. If I misunderstand how pull requests are merged (I've never done that), I'd be happy to try some voodoo. It'll take me a bit but probably be good for me :)

**Comment by jwass** [comment]
When you wrote it, I realized that it's a new Github feature. So that was the first time I used it.

Thanks!! Sorry for that super long delay.

**Pull request merged**
